### ISSUE TITLE
Not work for me

### ISSUE THREAD

**Issue by nixospu** [Zero3K/ERAM#17]
Hello. Trying to install your program latest version. Windows10 x64 Ukrainian version

Managed to disable windows forced driver signature check, and ram disk was created after install, but when I try run options eram.cpl it writes "Cannot open registy key" (but Eram registry key exist in Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Eram).

When PC was restarted in normal mode ram disk was not created. Options still not reachable with "Cannot open registy key" error.

**Comment by katahiromz** [comment]
KEY_WOW64_32KEY or UAC?

**Comment by Zero3K** [comment]
1. You have to keep using Driver Signature Enforcement disabled mode for it to work properly (until I can find a guy who can make a certificate that is either in my name or the name of the person who is making it).

2. Please try going to \Windows\System32 and right clicking the eram.cpl in it and then clicking Run as administrator (until I get the guy who is working on the driver to make an application that does what the CPL does, which will cause Windows to notify the user that the application is wanting to make changes).

**Comment by Zero3K** [comment]
Any news?

**Comment by Zero3K** [comment]
Any news?

**Comment by heldersepu** [comment]
I was getting the "Cannot open registry key" error and clicking Run as administrator did the job

**Comment by Zero3K** [comment]
Could you work on it?

**Comment by heldersepu** [comment]
@Zero3K work on what?

**Comment by Zero3K** [comment]
ERAM

**Comment by heldersepu** [comment]
Can you be more specific?

**Comment by Zero3K** [comment]
https://github.com/Zero3K/ERAM/issues/15
https://github.com/Zero3K/ERAM/issues/12
https://github.com/Zero3K/ERAM/issues/2

Also, signing the driver would be nice.

**Comment by heldersepu** [comment]
Sorry I just tested LmDisk:
https://sourceforge.net/projects/imdisk-toolkit/
and that is a much better alternative than this

**Comment by Zero3K** [comment]
@nixospu did you get it working?

**Comment by Zero3K** [comment]
@nixospu Well?

**Comment by Zero3K** [comment]
Did you get it working? Or should I close this issue since you're not responding?

**Comment by bl-ue** [comment]
Definitely close it, @Zero3K.  It's been over two years now.
