### ISSUE TITLE
How would I installed the build output

### ISSUE THREAD

**Issue by thulka** [Zero3K/ERAM#18]
Build output is the sys file, the driver. How would I install that? There is not any inf file in the project as well, which makes me wonder because there are issues about translation issues of the inf files.

How to install?

**Comment by Zero3K** [comment]
1. Move the .sys to C:\Windows\System32\drivers.
2. Rename the attached eram.reg.txt to eram.reg, and open it. 
3. Restart the PC into Driver Signature Enforcement Disabled Mode.

[eram.reg.txt](https://github.com/Zero3K/ERAM/files/2877724/eram.reg.txt)

You'll then end up with a 4 GB RAM Disk that is associated with the drive letter of R.

**Comment by Zero3K** [comment]
Please check out the new version available (v2.30) in the Releases page.
