### ISSUE TITLE
Where is "download in the Releases section"?

### ISSUE THREAD

**Issue by paulvi** [Zero3K/ERAM#19]
Where is "download in the Releases section" noted in README ? GitHub Releases are not enabled for this project.

How to download?

**Comment by Zero3K** [comment]
https://github.com/Zero3K/ERAM/releases

**Comment by paulvi** [comment]
Oh, yes, my eyes did no see

![image](https://user-images.githubusercontent.com/1614482/53611756-9ba2fb80-3c0a-11e9-9eab-1c905a2398b2.png)
