### ISSUE TITLE
BSOD on Windows 7/10 64-bit

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/ERAM#2]
It crashes when loading the OS with it active no matter the size that was chosen.

**Comment by Zero3K** [comment]
Now it just results in an "Automatic Repair" loop.

**Comment by Zero3K** [comment]
The second problem was because it was unsigned, which is now fixed thanks to the developer of ImDisk. I have managed to get an analysis of the BSOD in question. I am attaching it to this comment.

[eram_bsod_analysis.txt](https://github.com/Zero3K/ERAM/files/2591949/eram_bsod_analysis.txt)

**Comment by Zero3K** [comment]
Here's a conversation I had on IRC regarding it:

https://pastebin.com/H9ZPYz3M

**Comment by katahiromz** [comment]
I cannot afford to do. Sorry.

**Comment by Zero3K** [comment]
Okay.

**Comment by mshakurov** [comment]
Last version - the failure to load OS.

Parameters:

Drive = M:
Alloc unit = 32
Disk size = 500 000
Rootdir ent = 128
Media ID = F8
Memory source = OS: NonPaged pool
Local device = [checked on]
Make TEMP dir = [checked on]

To restore the OS boot, I deleted the eram file.sys from the command line. while booting.
Is there a help on the parameters? I'm afraid to experiment further )))
Thank you.

**Comment by Zero3K** [comment]
Please try the latest version (using the correct one for your OS's architecture) and make sure to boot into Driver Signature Enforcement disabled mode after installing it.

**Comment by Zero3K** [comment]
Any luck?

**Comment by Zero3K** [comment]
Any news?

**Comment by Zero3K** [comment]
@mshakurov Have you gotten it to work? Regarding the issue you're having, I will fix it by buying an EV code signing certificate and dongle, etc. with the money I'm getting for my birthday (which is in a little over a month) and making a new version that uses it.

**Comment by Zero3K** [comment]
I just tried a fresh build of it and have been able to use an 8 GB RAM Disk with no crashes under Windows 7 x64. So, I am closing this issue since it has been fixed for a while now.
