### ISSUE TITLE
How can I uninstall? 

### ISSUE THREAD

**Issue by jatiyanon** [Zero3K/ERAM#21]
ERAM_x64.exe on Windows 10
I want to uninstall but can't find the way out.

**Comment by Zero3K** [comment]
1. Run Regedit32 via the Run dialog accessible by pressing Win + R.
2. Delete the HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Eram key by clicking on it and pressing the Delete key.
3. Reboot your PC.
4. Delete the eram.sys located in \Windows\System32\drivers and the eram.cpl located in \Windows\System32 (if you downloaded it to that location).

**Comment by Zero3K** [comment]
I used a new installer that also comes with an uninstaller. So, this issue is now fixed.
