### ISSUE TITLE
not a issue

### ISSUE THREAD

**Issue by vvviperrr** [Zero3K/ERAM#4]
sry for writing here. i saw u interesting in reverse tethering (gnirethet). u can try and test my impl of reverse tethering https://github.com/vvviperrr/SimpleRT, i will be very appreciated.

**Comment by Zero3K** [comment]
I am running Windows 7. Please provide a cli for it that runs on the mentioned OS and I will test it. Thanks in advance.

**Comment by Zero3K** [comment]
Any news regarding it?
