### ISSUE TITLE
Better translation of "OS Outside Management Memory"

### ISSUE THREAD

**Issue by katahiromz** [Zero3K/ERAM#5]
"OS Outside Management Memory" is too long. Is there any better English translation?

**Comment by katahiromz** [comment]
Maybe "OS-managed memory" is better than "OS Management Memory".

**Comment by katahiromz** [comment]
"OS-unmanaged Memory" is much better than "OS Outside Management Memory".

**Comment by katahiromz** [comment]
@Zero3K How do you think?

**Comment by Zero3K** [comment]
That makes sense to me.

**Comment by katahiromz** [comment]
https://github.com/Zero3K/ERAM/pull/7

**Comment by Zero3K** [comment]
Thanks. Its been merged.
